/**
 * Image optimisation → responsive WebP variants + tiny blurred placeholders (LQIP).
 *
 *   node scripts/optimize-images.mjs
 *
 * Originals are left untouched. For each image it writes, next to the original:
 *   name.webp          – the LARGEST variant (used for big / retina screens)
 *   name-<w>.webp      – smaller variants, chosen by the browser via srcset (phones get these)
 * and it writes src/data/lqip.js: a ~200-byte blurred preview per photo, shown instantly while the
 * real image downloads (so slow connections see a soft preview, never an empty box).
 *
 * Re-run after adding images (npm run seo:assets).
 */
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const pub = path.join(process.cwd(), "public");

/** [directory, extensions, widths (ascending; last = main file), quality, wantsLqip] */
const jobs = [
  ["logos", [".png", ".jpg", ".jpeg"], [192], 80, false], // client logos: shown at ≤96px
  ["posters", [".jpg", ".jpeg", ".png"], [360, 600, 900], 74, true], // wall tiles + poster carousel
  ["clients", [".jpg", ".jpeg", ".png"], [360, 720], 74, true], // testimonial portraits
  [path.join("parallax", "logos"), [".png"], [640], 80, false], // brand tiles in the wall
];

let before = 0;
let after = 0;
const lqip = {};

for (const [dir, exts, widths, quality, wantsLqip] of jobs) {
  const abs = path.join(pub, dir);
  if (!fs.existsSync(abs)) continue;
  for (const file of fs.readdirSync(abs)) {
    const ext = path.extname(file).toLowerCase();
    if (!exts.includes(ext)) continue;
    const base = path.basename(file, path.extname(file));
    const src = path.join(abs, file);
    const original = fs.statSync(src).size;
    before += original;

    const sizes = [];
    for (const [i, width] of widths.entries()) {
      const isMain = i === widths.length - 1;
      const out = path.join(abs, isMain ? `${base}.webp` : `${base}-${width}.webp`);
      await sharp(src)
        .rotate() // honour EXIF orientation before metadata is dropped
        .resize({ width, withoutEnlargement: true })
        .webp({ quality, effort: 5 })
        .toFile(out);
      const size = fs.statSync(out).size;
      sizes.push(`${width}w ${(size / 1024).toFixed(0)}KB`);
      if (isMain) after += size;
    }

    if (wantsLqip) {
      const buf = await sharp(src).rotate().resize({ width: 16 }).webp({ quality: 40 }).toBuffer();
      lqip[`/${dir.replace(/\\/g, "/")}/${base}.webp`] = `data:image/webp;base64,${buf.toString("base64")}`;
    }
    console.log(`${path.join(dir, file).padEnd(34)} ${(original / 1024).toFixed(0).padStart(6)} KB → ${sizes.join(" · ")}`);
  }
}

fs.writeFileSync(
  path.join(process.cwd(), "src", "data", "lqip.js"),
  `/** GENERATED by scripts/optimize-images.mjs — do not edit. Tiny blurred previews keyed by image path. */\nexport const LQIP = ${JSON.stringify(lqip, null, 1)};\n`
);
console.log(`\nlqip.js: ${Object.keys(lqip).length} placeholders, ${(fs.statSync("src/data/lqip.js").size / 1024).toFixed(1)} KB`);

// Brand logo: a 512×512 PNG for structured data / app icons, plus a tiny WebP for the on-page card.
const logoSrc = path.join(pub, "tf-profile.png");
await sharp(logoSrc).resize(512, 512).png({ compressionLevel: 9 }).toFile(path.join(pub, "logo-512.png"));
await sharp(logoSrc).resize(128, 128).webp({ quality: 85 }).toFile(path.join(pub, "logo-128.webp"));
console.log(`Main files: ${(before / 1048576).toFixed(1)} MB → ${(after / 1048576).toFixed(1)} MB`);
